# Generated by Django 3.0.3 on 2020-06-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200607_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
